# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_phase_name', models.CharField(max_length=256)),
                ('migration_phase_description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_step', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Staus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemebers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=256)),
                ('member_phone', models.ImageField(max_length=20, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_type_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_type', to='mig_status.TeamType'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='migration_step_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_step_status', to='mig_status.Staus'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='step_migration_accountable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_migration_accountable', to='mig_status.TeamMemebers'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='step_migration_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_migration_phase', to='mig_status.MigrationPhase'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='step_migration_responsiable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_migration_responsiable', to='mig_status.TeamMemebers'),
        ),
    ]
