# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staus',
            new_name='Status',
        ),
    ]
