# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0002_auto_20190115_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemebers',
            name='member_email',
            field=models.EmailField(default='ets@etstur.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammemebers',
            name='member_phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
