# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0003_auto_20190115_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationsteps',
            name='migration_step_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='migration_step_status', to='mig_status.Status'),
        ),
    ]
