# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0004_auto_20190115_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationsteps',
            name='migration_step_ends',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='migration_step_starts',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='migrationsteps',
            name='migration_step_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='migration_step_status', to='mig_status.Status'),
        ),
    ]
