# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0005_auto_20190115_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrationsteps',
            name='step_migration_phase',
        ),
        migrations.AddField(
            model_name='migrationphase',
            name='migration_steps',
            field=models.ManyToManyField(related_name='step_migration_phase', to='mig_status.MigrationSteps'),
        ),
        migrations.AlterField(
            model_name='migrationsteps',
            name='migration_step_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='migration_step_status', to='mig_status.Status'),
        ),
        migrations.AlterField(
            model_name='teammemebers',
            name='member_phone',
            field=models.IntegerField(),
        ),
    ]
