# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0006_auto_20190115_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationsteps',
            name='step_migration_Informed',
            field=models.ManyToManyField(blank=True, related_name='step_migration_Informed', to='mig_status.TeamMemebers'),
        ),
        migrations.AddField(
            model_name='migrationsteps',
            name='step_migration_consulted',
            field=models.ManyToManyField(blank=True, related_name='step_migration_consulted', to='mig_status.TeamMemebers'),
        ),
    ]
