# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0007_auto_20190116_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemebers',
            name='member_email',
            field=models.EmailField(blank=True, default='ets@etstur.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teammemebers',
            name='member_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
