# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mig_status', '0008_auto_20190116_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemebers',
            name='member_email',
        ),
        migrations.RemoveField(
            model_name='teammemebers',
            name='member_phone',
        ),
    ]
